#!/usr/bin/env bash
#
# generate-checksums.sh — record what is vendored, so drift is detectable.
#
# Run after re-vendoring the specification from Cabuya/cabuya.org, in the same
# commit as the files themselves. Never run to "fix" a failing integrity check:
# if `verify-integrity.sh` fails, either somebody hand-edited a normative
# document — which is what the check is for — or an upstream version was
# vendored without its checksums, which is the same commit's job.
#
# Bash 3.2 compatible.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SPEC_DIR="$REPO_ROOT/spec"
CHECKSUMS="$SPEC_DIR/CHECKSUMS.txt"

sha256_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$1" | awk '{print $1}'
  else
    echo "ERROR: neither sha256sum nor shasum is available" >&2
    exit 2
  fi
}

if [ ! -d "$SPEC_DIR" ]; then
  echo "ERROR: spec/ does not exist." >&2
  exit 1
fi

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# SHA-256 of every vendored specification file."
  echo "#"
  echo "# Generated by scripts/generate-checksums.sh. Regenerate only when"
  echo "# re-vendoring from Cabuya/cabuya.org, in the same commit as the files."
  echo "#"
  echo "# Verified in CI by scripts/verify-integrity.sh: a vendored standard"
  echo "# nobody verifies is a fork nobody declared."
} > "$tmp"

count=0
# `sort` so the file is byte-stable across machines — otherwise every
# regeneration is a diff nobody can review.
while IFS= read -r file; do
  relative="${file#"$SPEC_DIR"/}"
  case "$relative" in
    CHECKSUMS.txt | .gitkeep) continue ;;
  esac
  echo "$(sha256_of "$file")  $relative" >> "$tmp"
  count=$((count + 1))
done <<INNER
$(find "$SPEC_DIR" -type f | sort)
INNER

if [ "$count" -eq 0 ]; then
  echo "Nothing vendored under spec/ — no checksums written."
  exit 0
fi

mv "$tmp" "$CHECKSUMS"
trap - EXIT
echo "✅ wrote spec/CHECKSUMS.txt ($count file(s))"
